// Homepage scrolling, video lifecycle and accessible fallbacks. Uses the shared browser-check environment.
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const base = process.env.BASE_URL || 'http://127.0.0.1:8000';
const artifacts = path.resolve(__dirname, '../.preview');
fs.mkdirSync(artifacts, {recursive:true});
(async()=>{
 const browser = await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 try {
  const context = await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});
  const page = await context.newPage(); const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
  await page.goto(base);await page.waitForSelector('.motion-enabled');
  await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');
  const scroll = async y=>{await page.evaluate(y=>scrollTo(0,y),y);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))};
  const filmTop=await page.locator('.motion-film').evaluate(el=>el.getBoundingClientRect().top+scrollY);
  const state=()=>page.evaluate(()=>({scale:Number(getComputedStyle(document.querySelector('.film-frame')).transform.match(/matrix\(([^,]+)/)?.[1]||1),brand:Number(document.querySelector('.journal-masthead').style.getPropertyValue('--brand-progress')),tail:document.querySelector('.wordmark-tail').getBoundingClientRect().width,headerTop:document.querySelector('.journal-masthead').getBoundingClientRect().top}));
  await scroll(0);const start=await state();assert.equal(start.brand,0);assert.ok(start.tail>30);
  await page.screenshot({path:path.join(artifacts,'motion-top.png')});
  await scroll(filmTop-650);const approaching=await state();
  await page.waitForFunction(()=>!document.querySelector('#field-film').paused);
  const time=await page.locator('video').evaluate(v=>v.currentTime);
  await page.waitForFunction(t=>document.querySelector('#field-film').currentTime>t+.15,time);
  await scroll(filmTop+350);const expanded=await state();
  assert.ok(expanded.scale>approaching.scale+.06,JSON.stringify({approaching,expanded}));
  assert.equal(expanded.brand,1);assert.ok(expanded.tail<1);assert.ok(Math.abs(expanded.headerTop)<2);
  await page.screenshot({path:path.join(artifacts,'motion-film-expanded.png')});
  await page.locator('.film-toggle').click();assert.ok(await page.locator('video').evaluate(v=>v.paused));
  await scroll(0);await scroll(filmTop+100);assert.ok(await page.locator('video').evaluate(v=>v.paused),'manual pause survives re-entry');
  await page.locator('.film-toggle').click();await page.waitForFunction(()=>!document.querySelector('#field-film').paused);
  await scroll(0);await page.waitForFunction(()=>document.querySelector('#field-film').paused);
  assert.equal((await state()).brand,0);assert.ok((await state()).tail>30);
  const card=page.locator('.ai-card').first();assert.equal(await card.evaluate(el=>getComputedStyle(el).opacity),'0');
  await card.scrollIntoViewIfNeeded();await page.waitForFunction(()=>getComputedStyle(document.querySelector('.ai-card')).opacity==='1');
  await page.screenshot({path:path.join(artifacts,'motion-reveal.png')});
  console.log('PASS: reversible brand collapse, sticky header, scroll-linked video growth, actual playback, pause/resume/offscreen lifecycle and content reveal.');
  for(const width of [320,390,768,1024,1440]){
   await page.setViewportSize({width,height:900});await scroll(0);
   const top=await page.locator('.motion-film').evaluate(el=>el.getBoundingClientRect().top+scrollY);
   await scroll(top+120);
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow at ${width}`);
   if(width===390)await page.screenshot({path:path.join(artifacts,'motion-mobile.png')});
  }
  await page.setViewportSize({width:320,height:900});await page.evaluate(()=>window.CutusPreferences.setFont(22));
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'22px font overflow');
  await page.evaluate(()=>window.CutusPreferences.setFont(16));
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>!document.body.classList.contains('motion-enabled'));
  assert.equal(await page.locator('.motion-enabled').count(),0);
  assert.ok(await page.locator('video').evaluate(v=>v.paused));
  assert.ok(await page.locator('.ai-card').first().evaluate(el=>getComputedStyle(el).opacity==='1'));
  await page.locator('.film-frame').scrollIntoViewIfNeeded();
  await page.locator('.film-toggle').click();await page.waitForFunction(()=>!document.querySelector('#field-film').paused);
  await page.locator('.film-toggle').click();
  console.log('PASS: five viewport sizes, large font, live reduced-motion change, visible content and manual playback.');
  const noJS=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:900}});
  const staticPage=await noJS.newPage();await staticPage.goto(base);
  assert.ok(await staticPage.locator('video').evaluate(v=>v.controls));
  assert.equal(await staticPage.locator('.film-toggle').isVisible(),false);
  assert.equal(await staticPage.locator('.motion-enabled').count(),0);
  assert.ok(await staticPage.locator('.ai-card').first().evaluate(el=>getComputedStyle(el).opacity==='1'));
  await noJS.close();
  const failed=await browser.newContext({viewport:{width:1440,height:1000}});
  await failed.route('**/*.mp4',r=>r.abort());const fallback=await failed.newPage();await fallback.goto(base);
  await fallback.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';const el=document.querySelector('.motion-film');scrollTo(0,el.getBoundingClientRect().top+scrollY+100)});
  await fallback.waitForFunction(()=>document.querySelector('.film-status').textContent.includes('暂不可用'));
  assert.ok(await fallback.locator('.film-link').isVisible());await failed.close();
  assert.deepEqual(errors,[]);
  console.log('PASS: no-JavaScript content, video failure fallback, zero page/resource errors.');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
